//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.HOT_BookInf {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblBookInfoId;
		protected global::System.Web.UI.WebControls.TextBox txtBookClassId;
		protected global::System.Web.UI.WebControls.TextBox txtBookName;
		protected global::System.Web.UI.WebControls.TextBox txtISBN;
		protected global::System.Web.UI.WebControls.TextBox txtAuthor;
		protected global::System.Web.UI.WebControls.TextBox txtTranslator;
		protected global::System.Web.UI.WebControls.TextBox txtInvestigator;
		protected global::System.Web.UI.WebControls.TextBox txtBookConcern;
		protected global::System.Web.UI.WebControls.TextBox txtBookSize;
		protected global::System.Web.UI.WebControls.TextBox txtPrintSheet;
		protected global::System.Web.UI.WebControls.TextBox txtWords;
		protected global::System.Web.UI.WebControls.TextBox txtPublishYear;
		protected global::System.Web.UI.WebControls.TextBox txtEdition;
		protected global::System.Web.UI.WebControls.TextBox txtPrintTime;
		protected global::System.Web.UI.WebControls.TextBox txtPrintNum;
		protected global::System.Web.UI.WebControls.TextBox txtBookPrice;
		protected global::System.Web.UI.WebControls.TextBox txtBindingId;
		protected global::System.Web.UI.WebControls.TextBox txtPages;
		protected global::System.Web.UI.WebControls.TextBox txtImages;
		protected global::System.Web.UI.WebControls.TextBox txtState;
		protected global::System.Web.UI.WebControls.TextBox txtRecommendation;
		protected global::System.Web.UI.WebControls.TextBox txtContent;
		protected global::System.Web.UI.WebControls.TextBox txtList;
		protected global::System.Web.UI.WebControls.TextBox txtDownLoad;
		protected global::System.Web.UI.WebControls.TextBox txtDate1;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;

    }
}
