//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.HOT_SoldBook {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtGrade;
		protected global::System.Web.UI.WebControls.TextBox txtBookPrice;
		protected global::System.Web.UI.WebControls.TextBox txtNumber;
		protected global::System.Web.UI.WebControls.TextBox txtDescription;
		protected global::System.Web.UI.WebControls.TextBox txtDate1;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;

    }
}
