//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.HOT_Config {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblSiteName;
	protected global::System.Web.UI.WebControls.Label lblSiteUrl;
	protected global::System.Web.UI.WebControls.Label lblWebmasterName;
	protected global::System.Web.UI.WebControls.Label lblWebmasterEmail;
	protected global::System.Web.UI.WebControls.Label lblCopyright;
	protected global::System.Web.UI.WebControls.Label lblHitsOfHot;
	protected global::System.Web.UI.WebControls.Label lblEnableUserReg;
	protected global::System.Web.UI.WebControls.Label lblUserName_RegDisabled;
	protected global::System.Web.UI.WebControls.Label lblUserNumber;
	protected global::System.Web.UI.WebControls.Label lblBookNumber;

    }
}
