//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.HOT_BookInf {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblBookInfoId;
	protected global::System.Web.UI.WebControls.Label lblBookClassId;
	protected global::System.Web.UI.WebControls.Label lblBookName;
	protected global::System.Web.UI.WebControls.Label lblISBN;
	protected global::System.Web.UI.WebControls.Label lblAuthor;
	protected global::System.Web.UI.WebControls.Label lblTranslator;
	protected global::System.Web.UI.WebControls.Label lblInvestigator;
	protected global::System.Web.UI.WebControls.Label lblBookConcern;
	protected global::System.Web.UI.WebControls.Label lblBookSize;
	protected global::System.Web.UI.WebControls.Label lblPrintSheet;
	protected global::System.Web.UI.WebControls.Label lblWords;
	protected global::System.Web.UI.WebControls.Label lblPublishYear;
	protected global::System.Web.UI.WebControls.Label lblEdition;
	protected global::System.Web.UI.WebControls.Label lblPrintTime;
	protected global::System.Web.UI.WebControls.Label lblPrintNum;
	protected global::System.Web.UI.WebControls.Label lblBookPrice;
	protected global::System.Web.UI.WebControls.Label lblBindingId;
	protected global::System.Web.UI.WebControls.Label lblPages;
	protected global::System.Web.UI.WebControls.Label lblImages;
	protected global::System.Web.UI.WebControls.Label lblState;
	protected global::System.Web.UI.WebControls.Label lblRecommendation;
	protected global::System.Web.UI.WebControls.Label lblContent;
	protected global::System.Web.UI.WebControls.Label lblList;
	protected global::System.Web.UI.WebControls.Label lblDownLoad;
	protected global::System.Web.UI.WebControls.Label lblAddDate;

    }
}
