//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.HOT_User {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtRoleID;
		protected global::System.Web.UI.WebControls.TextBox txtUserType;
		protected global::System.Web.UI.WebControls.TextBox txtUserName;
		protected global::System.Web.UI.WebControls.TextBox txtUserPassword;
		protected global::System.Web.UI.WebControls.TextBox txtQuestion;
		protected global::System.Web.UI.WebControls.TextBox txtAnswer;
		protected global::System.Web.UI.WebControls.TextBox txtEmail;
		protected global::System.Web.UI.WebControls.TextBox txtAddress;
		protected global::System.Web.UI.WebControls.TextBox txtPostCode;
		protected global::System.Web.UI.WebControls.TextBox txtTelephone;
		protected global::System.Web.UI.WebControls.TextBox txtMobile;
		protected global::System.Web.UI.WebControls.TextBox txtQQ;
		protected global::System.Web.UI.WebControls.TextBox txtUserFace;
		protected global::System.Web.UI.WebControls.TextBox txtDate1;
		protected global::System.Web.UI.WebControls.TextBox txtDate1;
		protected global::System.Web.UI.WebControls.TextBox txtLastLoginIP;
		protected global::System.Web.UI.WebControls.TextBox txtLoginTimes;
		protected global::System.Web.UI.WebControls.TextBox txtUserPoint;
		protected global::System.Web.UI.WebControls.TextBox txtUserBooks;
		protected global::System.Web.UI.WebControls.TextBox txtConsumePoint;
		protected global::System.Web.UI.WebControls.TextBox txtUnreadMsg;
		protected global::System.Web.UI.WebControls.TextBox txtIsLocked;
		protected global::System.Web.UI.WebControls.TextBox txtUserSetting;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;

    }
}
