//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.HOT_User {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblUserID;
	protected global::System.Web.UI.WebControls.Label lblRoleID;
	protected global::System.Web.UI.WebControls.Label lblUserType;
	protected global::System.Web.UI.WebControls.Label lblUserName;
	protected global::System.Web.UI.WebControls.Label lblUserPassword;
	protected global::System.Web.UI.WebControls.Label lblQuestion;
	protected global::System.Web.UI.WebControls.Label lblAnswer;
	protected global::System.Web.UI.WebControls.Label lblEmail;
	protected global::System.Web.UI.WebControls.Label lblAddress;
	protected global::System.Web.UI.WebControls.Label lblPostCode;
	protected global::System.Web.UI.WebControls.Label lblTelephone;
	protected global::System.Web.UI.WebControls.Label lblMobile;
	protected global::System.Web.UI.WebControls.Label lblQQ;
	protected global::System.Web.UI.WebControls.Label lblUserFace;
	protected global::System.Web.UI.WebControls.Label lblRegTime;
	protected global::System.Web.UI.WebControls.Label lblLastLoginTime;
	protected global::System.Web.UI.WebControls.Label lblLastLoginIP;
	protected global::System.Web.UI.WebControls.Label lblLoginTimes;
	protected global::System.Web.UI.WebControls.Label lblUserPoint;
	protected global::System.Web.UI.WebControls.Label lblUserBooks;
	protected global::System.Web.UI.WebControls.Label lblConsumePoint;
	protected global::System.Web.UI.WebControls.Label lblUnreadMsg;
	protected global::System.Web.UI.WebControls.Label lblIsLocked;
	protected global::System.Web.UI.WebControls.Label lblUserSetting;

    }
}
