//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.HOT_Config {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtSiteName;
		protected global::System.Web.UI.WebControls.TextBox txtSiteUrl;
		protected global::System.Web.UI.WebControls.TextBox txtWebmasterName;
		protected global::System.Web.UI.WebControls.TextBox txtWebmasterEmail;
		protected global::System.Web.UI.WebControls.TextBox txtCopyright;
		protected global::System.Web.UI.WebControls.TextBox txtHitsOfHot;
		protected global::System.Web.UI.WebControls.TextBox txtEnableUserReg;
		protected global::System.Web.UI.WebControls.TextBox txtUserName_RegDisabled;
		protected global::System.Web.UI.WebControls.TextBox txtUserNumber;
		protected global::System.Web.UI.WebControls.TextBox txtBookNumber;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;

    }
}
